<?php

namespace ContainerNUxAmB2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ek4zuIRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ek4zuIR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ek4zuIR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cardRepository' => ['privates', 'App\\Repository\\CardRepository', 'getCardRepositoryService', true],
            'game' => ['privates', '.errored..service_locator.Ek4zuIR.App\\Entity\\Game', NULL, 'Cannot autowire service ".service_locator.Ek4zuIR": it references class "App\\Entity\\Game" but no such service exists.'],
        ], [
            'cardRepository' => 'App\\Repository\\CardRepository',
            'game' => 'App\\Entity\\Game',
        ]);
    }
}
