<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRRxRPck\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRRxRPck/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRRxRPck.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRRxRPck\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRRxRPck\App_KernelDevDebugContainer([
    'container.build_hash' => 'RRxRPck',
    'container.build_id' => 'd14c4277',
    'container.build_time' => 1616098169,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRRxRPck');
